# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8ecb2c53b68f9fe892dad9b318143e23"
name = "shop-sheet"
handle = "shop-sheet"
application_url = "https://late-kick-fw-needs.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://late-kick-fw-needs.trycloudflare.com/auth/callback", "https://late-kick-fw-needs.trycloudflare.com/auth/shopify/callback", "https://late-kick-fw-needs.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
